#!/usr/bin/env bash
# Prints the record type and destination of subdomains
display_dom() {	
    rec=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '/IN/ { print $4 }')
    ip_add=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '/IN/ { print $5 }')
    echo "The subdomain $2 is a $rec record and points to $ip_add"
    }

# Displays the record and destination when the args are less or equal to two
if [ $# -eq 2 ]
then
    display_dom "$1" "$2"
elif [ $# -eq 1 ]
# Displays the record and destination when there's only one argument
then
    display_dom "$1" "www"
    display_dom "$1" "lb-01"
    display_dom "$1" "web-01"
    display_dom "$1" "web-02"
fi
