#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.

sudo service nginx stop
sudo pkill apache2

# Set user in the config file
sudo sed -i 's/#user nginx/user nginx/' /etc/nginx/nginx.conf

#Set listen directives
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx start
